# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FinalVote(object):
    def setupUi(self, FinalVote):
        FinalVote.setObjectName("FinalVote")
        FinalVote.resize(300, 400)
        FinalVote.setMinimumSize(QtCore.QSize(300, 400))
        FinalVote.setMaximumSize(QtCore.QSize(300, 400))
        self.SubmitButton = QtWidgets.QPushButton(parent=FinalVote)
        self.SubmitButton.setGeometry(QtCore.QRect(90, 230, 131, 51))
        self.SubmitButton.setObjectName("SubmitButton")
        self.JaneButton = QtWidgets.QRadioButton(parent=FinalVote)
        self.JaneButton.setGeometry(QtCore.QRect(130, 150, 71, 31))
        self.JaneButton.setObjectName("JaneButton")
        self.JohnButton = QtWidgets.QRadioButton(parent=FinalVote)
        self.JohnButton.setGeometry(QtCore.QRect(130, 180, 71, 31))
        self.JohnButton.setObjectName("JohnButton")
        self.Candidates_label = QtWidgets.QLabel(parent=FinalVote)
        self.Candidates_label.setGeometry(QtCore.QRect(0, 110, 301, 51))
        self.Candidates_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Candidates_label.setObjectName("Candidates_label")
        self.Id_label = QtWidgets.QLabel(parent=FinalVote)
        self.Id_label.setGeometry(QtCore.QRect(80, 90, 16, 16))
        self.Id_label.setObjectName("Id_label")
        self.Id_lineEdit = QtWidgets.QLineEdit(parent=FinalVote)
        self.Id_lineEdit.setGeometry(QtCore.QRect(110, 90, 113, 20))
        self.Id_lineEdit.setObjectName("Id_lineEdit")
        self.VotingApplication_label = QtWidgets.QLabel(parent=FinalVote)
        self.VotingApplication_label.setGeometry(QtCore.QRect(0, 60, 301, 20))
        self.VotingApplication_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VotingApplication_label.setObjectName("VotingApplication_label")
        self.results_label = QtWidgets.QLabel(parent=FinalVote)
        self.results_label.setGeometry(QtCore.QRect(0, 300, 301, 81))
        self.results_label.setText("")
        self.results_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.results_label.setObjectName("results_label")

        self.retranslateUi(FinalVote)
        QtCore.QMetaObject.connectSlotsByName(FinalVote)

    def retranslateUi(self, FinalVote):
        _translate = QtCore.QCoreApplication.translate
        FinalVote.setWindowTitle(_translate("FinalVote", "Dialog"))
        self.SubmitButton.setText(_translate("FinalVote", "SUBMIT VOTE"))
        self.JaneButton.setText(_translate("FinalVote", "Jane"))
        self.JohnButton.setText(_translate("FinalVote", "John"))
        self.Candidates_label.setText(_translate("FinalVote", "CANDIDATES"))
        self.Id_label.setText(_translate("FinalVote", "ID"))
        self.VotingApplication_label.setText(_translate("FinalVote", "Voting Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FinalVote = QtWidgets.QDialog()
    ui = Ui_FinalVote()
    ui.setupUi(FinalVote)
    FinalVote.show()
    sys.exit(app.exec())
